// =============================================
// OSINT Tools Configuration
// =============================================

const toolsData = [
  // ====== SEARCH TOOLS ======
  {
    id: "vt",
    name: "VirusTotal",
    template: "https://www.virustotal.com/gui/search/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Analyze suspicious files, domains, IPs & URLs",
  },
  {
    id: "urlscan",
    name: "URLScan",
    template: "https://urlscan.io/search/#{{query}}",
    category: "SEARCH_TOOLS",
    description: "Search for domains, IPs, filenames, hashes, ASNs",
  },
  {
    id: "shodan",
    name: "Shodan",
    template: "https://www.shodan.io/search?query={{query}}",
    category: "SEARCH_TOOLS",
    description: "Search Engine for the Internet of Everything",
  },
  {
    id: "scamalytics",
    name: "Scamalytics",
    template: "https://scamalytics.com/ip/{{query}}",
    category: "IP_INFO",
    description: "IP Address Fraud Check",
  },
  {
    id: "webcheck",
    name: "Web Check",
    template: "https://web-check.xyz/check/{{query}}",
    category: "SEARCH_TOOLS",
    description: "All-in-one OSINT website analyzer",
  },
  {
    id: "tormetrics",
    name: "Tor Metrics",
    template: "https://metrics.torproject.org/rs.html#search/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Tor Metrics Information",
  },
  {
    id: "intelx",
    name: "IntelX",
    template: "https://intelx.io/?s={{query}}",
    category: "SEARCH_TOOLS",
    description: "Enter a domain, URL, Email, IP, CIDR, Bitcoin address, and more",
  },
  {
    id: "hostio",
    name: "Host IO",
    template: "https://host.io/?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Domain and IP intelligence",
  },
  {
    id: "silentpush",
    name: "Silent Push",
    template: "https://explore.silentpush.com/enrichment/domain/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Search for domains, IPs, AS Numbers",
  },
  {
    id: "livescan",
    name: "Live Scan",
    template: "https://explore.silentpush.com/live-scan?url={{query}}",
    category: "SEARCH_TOOLS",
    description: "Silent Push Live Scan",
  },
  {
    id: "gsafebrowsing",
    name: "Google Safe Browsing",
    template: "https://transparencyreport.google.com/safe-browsing/search?url={{query}}",
    category: "SEARCH_TOOLS",
    description: "Identify dangerous sites, search for unsafe content",
  },
  {
    id: "urlhaus",
    name: "URLhaus",
    template: "https://urlhaus.abuse.ch/browse.php?search={{query}}",
    category: "SEARCH_TOOLS",
    description: "Malicious URL tracker",
  },
  {
    id: "hybridanalysis",
    name: "Hybrid Analysis",
    template: "https://www.hybrid-analysis.com/search?query={{query}}",
    category: "SEARCH_TOOLS",
    description: "Malware analysis & threat intelligence",
  },
  {
    id: "socradar",
    name: "SOC Radar IOC",
    template: "https://socradar.io/labs/app/ioc-radar?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Advanced threat intelligence search engine for analyzing IOCs",
  },
  {
    id: "pulsedive",
    name: "Pulsedive",
    template: "https://pulsedive.com/ioc/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Search any domain, IP, or URL and enrich on-demand",
  },
  {
    id: "abuseipdb",
    name: "Abuse IPDB",
    template: "https://www.abuseipdb.com/check/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Check the report history of any IP address",
  },
  {
    id: "whoisxml",
    name: "WhoisXML",
    template: "https://whois.whoisxmlapi.com/lookup?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Gather registration information from WHOIS records",
  },
  {
    id: "urlvoid",
    name: "URL Void",
    template: "https://www.urlvoid.com/scan/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Check the online reputation/safety of a website",
  },
  {
    id: "centralops",
    name: "CentralOps",
    template:
      "https://centralops.net/co/DomainDossier.aspx?addr={{query}}&_body=DomainDossier.aspx&dom_dns=true&dom_whois=true&net_whois=true",
    category: "SEARCH_TOOLS",
    description: "DNS/WHOIS for domains and IPs",
  },
  {
    id: "fortiguard",
    name: "Fortiguard",
    template: "https://www.fortiguard.com/search?q={{query}}&engine=7",
    category: "SEARCH_TOOLS",
    description: "Submit a Domain to search",
  },
  {
    id: "metadefender",
    name: "MetaDefender",
    template:
      "https://metadefender.opswat.com/results/domain/{{query}}/overview",
    category: "SEARCH_TOOLS",
    description: "Analyze a File, URL, IP, Hash or CVE",
  },
  {
    id: "sucuri",
    name: "Sucuri",
    template: "https://sitecheck.sucuri.net/results/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Check website for known malware, viruses, blacklisting status",
  },
  {
    id: "threatyeti",
    name: "Threat Yeti",
    template: "https://threatyeti.com/search?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Check a link-domain for malware or phishing",
  },
  {
    id: "mywot",
    name: "MyWOT",
    template: "https://www.mywot.com/scorecard/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Machine learning algorithms and blacklists",
  },
  {
    id: "crtsh",
    name: "crt.sh",
    template: "https://crt.sh/?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Certificate transparency records",
  },
  {
    id: "securitytrails",
    name: "Security Trails",
    template: "https://securitytrails.com/domain/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Domain & DNS data intelligence",
  },
  {
    id: "whoxy",
    name: "Whoxy",
    template: "https://www.whoxy.com/?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Domain Search Engine",
  },
  {
    id: "builtwith",
    name: "BuiltWith",
    template: "https://builtwith.com/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Find out what websites are Built With",
  },
  {
    id: "dnspropagation",
    name: "DNS Propagation",
    template: "https://dnschecker.org/#A/{{query}}",
    category: "SEARCH_TOOLS",
    description: "Check DNS Propagation",
  },
  {
    id: "dnsdumpster",
    name: "DNS Dumpster",
    template:
      "https://dnsdumpster.com/?target={{query}}&user=free",
    category: "SEARCH_TOOLS",
    description: "Passive DNS and domain mapping tool",
  },

  // ====== IP INFO ======
  {
    id: "ipinfo",
    name: "IPInfo",
    template: "https://ipinfo.io/{{query}}",
    category: "IP_INFO",
    description: "IP address geolocation and ISP information",
  },
  {
    id: "maxmind",
    name: "MaxMind GeoIP2",
    template: "https://www.maxmind.com/en/geoip2-precision-demo?ip={{query}}",
    category: "IP_INFO",
    description: "IP geolocation and threat data",
  },
  {
    id: "whoisip",
    name: "WHOIS IP",
    template: "https://www.whois.net/?query={{query}}",
    category: "IP_INFO",
    description: "IP WHOIS lookup",
  },

  // ====== THREAT INTELLIGENCE ======
  {
    id: "alienvault",
    name: "AlienVault OTX",
    template: "https://otx.alienvault.com/?q={{query}}",
    category: "THREAT_INTELLIGENCE",
    description: "Open Threat Intelligence community",
  },
  {
    id: "misp",
    name: "MISP",
    template: "https://www.misp-project.org/",
    category: "THREAT_INTELLIGENCE",
    description: "Malware Information Sharing Platform",
  },
  {
    id: "threatstream",
    name: "ThreatStream",
    template: "https://www.anomali.com/threat-intelligence",
    category: "THREAT_INTELLIGENCE",
    description: "Threat Intelligence Platform",
  },

  // ====== HASH LOOKUP ======
  {
    id: "md5online",
    name: "MD5Online",
    template: "https://www.md5online.org/?q={{query}}",
    category: "HASH_LOOKUP",
    description: "MD5, SHA1, SHA256 hash lookup",
  },
  {
    id: "hashkiller",
    name: "Hash Killer",
    template: "https://hashkiller.io/",
    category: "HASH_LOOKUP",
    description: "Hash reverse lookup database",
  },

  // ====== EMAIL ======
  {
    id: "haveibeenpwned",
    name: "Have I Been Pwned",
    template: "https://haveibeenpwned.com/?q={{query}}",
    category: "EMAIL",
    description: "Check if email has been compromised",
  },
  {
    id: "emailrep",
    name: "EmailRep",
    template: "https://emailrep.io/query?email={{query}}",
    category: "EMAIL",
    description: "Email address reputation and intelligence",
  },

  // ====== FILE & MALWARE ANALYSIS ======
  {
    id: "anyrun",
    name: "ANY.RUN",
    template: "https://any.run/?q={{query}}",
    category: "FILE_MALWARE_ANALYSIS",
    description: "Interactive online malware sandbox",
  },
  {
    id: "joesandbox",
    name: "Joe Sandbox",
    template: "https://www.joesecurity.org/",
    category: "FILE_MALWARE_ANALYSIS",
    description: "Malware analysis and detection service",
  },
  {
    id: "cuckoo",
    name: "Cuckoo Sandbox",
    template: "https://cuckoo.cert.ee/",
    category: "FILE_MALWARE_ANALYSIS",
    description: "Open-source malware analysis system",
  },

  // ====== MALWARE FEEDS ======
  {
    id: "malwarebazaar",
    name: "Malware Bazaar",
    template: "https://bazaar.abuse.ch/browse.php?search={{query}}",
    category: "MALWARE_FEEDS",
    description: "Malware samples database",
  },
  {
    id: "abusemalware",
    name: "Abuse.ch Malware",
    template: "https://abuse.ch/",
    category: "MALWARE_FEEDS",
    description: "Malware feeds and databases",
  },

  // ====== USERNAME & PEOPLE OSINT ======
  {
    id: "holehe",
    name: "Holehe",
    template: "https://holehe.io/?q={{query}}",
    category: "USERNAME_PEOPLE_OSINT",
    description: "Check if email exists on multiple sites",
  },
  {
    id: "sherlock",
    name: "Sherlock",
    url: "https://sherlock-project.github.io/",
    category: "USERNAME_PEOPLE_OSINT",
    description: "Hunt down social media accounts by username",
  },
  {
    id: "namechk",
    name: "Namechk",
    template: "https://namechk.com/?u={{query}}",
    category: "USERNAME_PEOPLE_OSINT",
    description: "Check username availability across sites",
  },

  // ====== WEBSITE OSINT TOOLS ======
  {
    id: "gtmetrix",
    name: "GTmetrix",
    template: "https://gtmetrix.com/?url={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Website performance analysis",
  },
  {
    id: "similarweb",
    name: "SimilarWeb",
    template: "https://www.similarweb.com/website/{{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Website analytics and competitive intelligence",
  },
  {
    id: "archive",
    name: "Wayback Machine",
    template: "https://web.archive.org/web/*/{{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Internet Archive for historical website versions",
  },

  // ====== REAL TIME THREAT MAPS ======
  {
    id: "threatmap",
    name: "Kaspersky Threat Map",
    template: "https://cybermap.kaspersky.com/",
    category: "REAL_TIME_THREAT_MAPS",
    description: "Real-time cyber attacks visualization",
  },
  {
    id: "netlab",
    name: "Netlab 360 Cyber Threat Map",
    template: "https://netlab.360.com/",
    category: "REAL_TIME_THREAT_MAPS",
    description: "Real-time cyber attacks and threat analytics",
  },

  // ====== CODE SEARCH ======
  {
    id: "github",
    name: "GitHub",
    template: "https://github.com/search?q={{query}}&type=code",
    category: "CODE_SEARCH",
    description: "Search code repositories",
  },
  {
    id: "gitlab",
    name: "GitLab",
    template: "https://gitlab.com/search?search={{query}}&nav_source=navbar",
    category: "CODE_SEARCH",
    description: "Search GitLab repositories",
  },
  {
    id: "shodan-code",
    name: "Shodan Exploits",
    template: "https://www.exploit-db.com/?q={{query}}",
    category: "CODE_SEARCH",
    description: "Exploit database and code search",
  },

  // ====== ADDITIONAL OSINT TOOLS ======
  {
    id: "sitechecker",
    name: "Site Checker",
    template: "https://sitechecker.pro/?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Website health check and monitoring",
  },
  {
    id: "nordvpn-ip-lookup",
    name: "NordVPN IP Lookup",
    template: "https://nordvpn.com/es/ip-lookup/?query={{query}}",
    category: "IP_INFO",
    description: "IP address geolocation and details",
  },
  {
    id: "downforeveryoneorjustme",
    name: "Down for Everyone or Just Me",
    template: "https://downforeveryoneorjustme.com/?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Check if a website is down for everyone",
  },
  {
    id: "redirectdetective",
    name: "Redirect Detective",
    template: "https://redirectdetective.com/?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Trace HTTP redirects",
  },
  {
    id: "mxtoolbox",
    name: "MXToolbox",
    template: "https://mxtoolbox.com/{{query}}",
    category: "DNS_TOOLS",
    description: "Email, DNS, blacklist, and network tools",
  },
  {
    id: "phishly",
    name: "Phish.ly",
    template: "https://phish.ly/?q={{query}}",
    category: "EMAIL",
    description: "Phishing detection and email analysis",
  },
  {
    id: "crackstation",
    name: "CrackStation",
    template: "https://crackstation.net/?q={{query}}",
    category: "HASH_LOOKUP",
    description: "Free online hash cracking service",
  },
  {
    id: "nordvpn-file-checker",
    name: "NordVPN File Checker",
    template: "https://nordvpn.com/es/file-checker/?q={{query}}",
    category: "FILE_MALWARE_ANALYSIS",
    description: "Malware and threat file scanning",
  },
  {
    id: "vt-upload",
    name: "VirusTotal Upload",
    template: "https://www.virustotal.com/gui/home/upload",
    category: "FILE_MALWARE_ANALYSIS",
    description: "Upload files for multi-engine malware analysis",
  },
  {
    id: "bgp-tools",
    name: "BGP.tools",
    template: "https://bgp.tools/?q={{query}}",
    category: "IP_INFO",
    description: "ASN, BGP, and IP routing information",
  },
  {
    id: "censys",
    name: "Censys",
    template: "https://search.censys.io/search?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Search for internet connected devices and certificates",
  },
  {
    id: "ssllabs",
    name: "SSL Labs",
    template: "https://www.ssllabs.com/ssltest/analyze.html?d={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "SSL/TLS certificate and security analysis",
  },
  {
    id: "nslookup",
    name: "NSLookup.io",
    template: "https://www.nslookup.io/{{query}}",
    category: "DNS_TOOLS",
    description: "DNS lookup and subdomain finder",
  },
  {
    id: "domaintools",
    name: "DomainTools WHOIS",
    template: "https://whois.domaintools.com/?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "WHOIS lookup with domain history",
  },
  {
    id: "cloudflare-radar",
    name: "Cloudflare Radar",
    template: "https://radar.cloudflare.com/?q={{query}}",
    category: "SEARCH_TOOLS",
    description: "Internet traffic and analytics insights",
  },
  {
    id: "sitecheck-sucuri",
    name: "Sucuri SiteCheck",
    template: "https://sitecheck.sucuri.net/?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Website malware and security scan",
  },
  {
    id: "mozilla-observatory",
    name: "Mozilla Observatory",
    template: "https://developer.mozilla.org/en-US/observatory?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Website security analysis and recommendations",
  },
  {
    id: "securityheaders",
    name: "SecurityHeaders",
    template: "https://securityheaders.com/?q={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Analyze HTTP security headers of a website",
  },
  {
    id: "multirbl",
    name: "MultiRBL",
    template: "https://multirbl.valli.org/lookup/{{query}}",
    category: "DNS_TOOLS",
    description: "Check IP address against multiple DNS blacklists (RBL/DNSBL)",
  },
  {
    id: "sitereport-netcraft",
    name: "Netcraft Site Report",
    template: "https://sitereport.netcraft.com/?url={{query}}",
    category: "WEBSITE_OSINT_TOOLS",
    description: "Site report and hosting history from Netcraft",
  },
];
