# These are supported funding model platforms

# github: [s3codecL] # Descomenta y agrega tu usuario si configuras GitHub Sponsors
# patreon: # Tu usuario de Patreon
# open_collective: # Tu proyecto en Open Collective
# ko_fi: # Tu usuario de Ko-fi
# tidelift: # Tu proyecto en Tidelift
# community_bridge: # Tu proyecto
# liberapay: # Tu usuario de Liberapay
# issuehunt: # Tu usuario de IssueHunt
# otechie: # Tu usuario de Otechie
# lfx_crowdfunding: # Tu proyecto en LFX Crowdfunding
# custom: # URL personalizada

# Descomenta las líneas de las plataformas que uses
# Ejemplo:
# github: s3codecL
# ko_fi: aegisdashboard
